services:
  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    ports:
      - "0.0.0.0:5001:5000"
    volumes:
      - registry-data:/var/lib/registry

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "5001:5001"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config

volumes:
  registry-data:
  caddy-data:
  caddy-config:
