# yaml-language-server schema=https://taskfile.dev/schema.json

version: "3"

dotenv:
  - .env

includes:
  k3s:
    taskfile: k3s/Taskfile.yaml

  tofu:
    taskfile: ./tofu/Taskfile.yaml
    dir: ./tofu/
