# yaml-language-server schema=https://taskfile.dev/schema.json

version: "3"

dotenv:
  - .env

includes:
  k3s: k3s/Taskfile.yml
  homepage: homepage/Taskfile.yml

tasks:
  install:
    desc: Install k3s
    cmds:
      - curl -sfL https://get.k3s.io | sh -

  run:
    desc: Start local image registry
    cmds:
      - ./scripts/start-image-registry.sh
