# yaml-language-server schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  start-registry:
    desc: Start local image registry
    cmds:
      - ./scripts/start-image-registry.sh

  install-k3s:
    desc: Install k3s
    cmds:
      - curl -sfL https://get.k3s.io | sh -

  traefik:
    desc: Sync Traefik configuration to k3s
    cmds:
      - sudo mkdir -p /var/lib/rancher/k3s/server/manifests/
      - sudo install -m 0644 ./k3s/traefik/helmchartconfig.yaml /var/lib/rancher/k3s/server/manifests/traefik-config.yaml
      - sudo install -m 0644 ./k3s/registries/registries.yaml /etc/rancher/k3s/registries.yaml
      - sudo systemctl restart k3s

  apply:
    desc: Sync all k3s resources
    deps:
      - traefik
    cmds:
      - kubectl apply -f k3s/cert-manager/
      - kubectl apply -f k3s/apps/
